using Content.Shared.Preferences;
using Content.Shared._CD.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Content.Client.Lobby.UI;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._CD.Records.UI;

/// <summary>
/// The record editor tab that gets "injected" into the character editor.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RecordEditorGui : Control
{
    /// <summary>
    /// Delegate that tells the editor to save records when the save button is pressed
    /// </summary>
    private readonly Action<PlayerProvidedCharacterRecords> _updateProfileRecords;
    public PlayerProvidedCharacterRecords Records
    {
        get;
        private set;
    } = default!;
    private HumanoidProfileEditor _profileEditor;

    public RecordEditorGui(Action<PlayerProvidedCharacterRecords> updateProfileRecords, HumanoidProfileEditor profileEditor)
    {
        RobustXamlLoader.Load(this);
        _updateProfileRecords = updateProfileRecords;
        _profileEditor = profileEditor;

        #region General

        HeightEdit.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newHeight))
                return;
            UpdateImperialHeight(newHeight);

            if (!_profileEditor.DoSizeActions)
                return;

            _profileEditor.FindControl<Slider>("HeightSlider").Value = newHeight;
            _profileEditor.SetCharacterHeight(newHeight);
            // UpdateRecords(Records.WithHeight(newHeight));
        };

        WeightEdit.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newWeight))
                return;
            UpdateImperialWeight(newWeight);

            if (!_profileEditor.DoSizeActions)
                return;

            UpdateRecords(Records.WithWeight(newWeight));
        };

        ContactNameEdit.OnTextChanged += args =>
        {
            UpdateRecords(Records.WithContactName(args.Text));
        };

        #endregion

        #region Employment

        WorkAuthCheckBox.OnToggled += args =>
        {
            UpdateRecords(Records.WithWorkAuth(args.Pressed));
        };

        #endregion

        #region Security

        IdentifyingFeaturesEdit.OnTextChanged += args =>
        {
            UpdateRecords(Records.WithIdentifyingFeatures(args.Text));
        };

        #endregion

        #region Medical

        AllergiesEdit.OnTextChanged += args =>
        {
            UpdateRecords(Records.WithAllergies(args.Text));
        };

        DrugAllergiesEdit.OnTextChanged += args =>
        {
            UpdateRecords(Records.WithDrugAllergies(args.Text));
        };

        PostmortemEdit.OnTextChanged += args =>
        {
            UpdateRecords(Records.WithPostmortemInstructions(args.Text));
        };

        #endregion

        #region Entries

        EntryEditorTabs.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-cd-records-employment"));
        EntryEditorTabs.SetTabTitle(1, Loc.GetString("department-Medical"));
        EntryEditorTabs.SetTabTitle(2, Loc.GetString("department-Security"));

        EmploymentEntrySelector.OnUpdateEntries += args =>
        {
            UpdateRecords(Records.WithEmploymentEntries(args.Entries));
        };

        MedicalEntrySelector.OnUpdateEntries += args =>
        {
            UpdateRecords(Records.WithMedicalEntries(args.Entries));
        };

        SecurityEntrySelector.OnUpdateEntries += args =>
        {
            UpdateRecords(Records.WithSecurityEntries(args.Entries));
        };

        #endregion
    }

    public void Update(HumanoidCharacterProfile? profile)
    {
        Records = profile?.CDCharacterRecords ?? PlayerProvidedCharacterRecords.DefaultRecords();
        EmploymentEntrySelector.UpdateContents(Records.EmploymentEntries);
        MedicalEntrySelector.UpdateContents(Records.MedicalEntries);
        SecurityEntrySelector.UpdateContents(Records.SecurityEntries);
        UpdateWidgets();
    }

    public void UpdateRecords(PlayerProvidedCharacterRecords records)
    {
        records.EnsureValid();
        Records = records;
        _updateProfileRecords(Records);
        UpdateWidgets();
    }

    private void UpdateWidgets()
    {
        if (_profileEditor is not null && _profileEditor.Profile is not null)
        {
            HeightEdit.SetText(_profileEditor.Profile.Height.ToString());
            UpdateImperialHeight(_profileEditor.Profile.Height);
        }
        WeightEdit.SetText(Records.Weight.ToString());
        UpdateImperialWeight(Records.Weight);
        ContactNameEdit.SetText(Records.EmergencyContactName);

        WorkAuthCheckBox.Pressed = Records.HasWorkAuthorization;

        IdentifyingFeaturesEdit.SetText(Records.IdentifyingFeatures);

        AllergiesEdit.SetText(Records.Allergies);
        DrugAllergiesEdit.SetText(Records.DrugAllergies);
        PostmortemEdit.SetText(Records.PostmortemInstructions);
    }

    public void UpdateImperialHeight(int newHeight)
    {
        HeightImperialLabel.Text = UnitConversion.GetImperialDisplayLength(newHeight);
    }

    private void UpdateImperialWeight(int newWeight)
    {
        WeightImperialLabel.Text = UnitConversion.GetImperialDisplayMass(newWeight);
    }
}
